# Generated by Django 4.2.13 on 2026-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
